import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useLanguage } from '../context/LanguageContext';
import { useAuth } from '../context/AuthContext';
import { User } from '../types';
import { Check, UserPlus, Lock, Edit, X, ChevronLeft } from 'lucide-react';

export const AdminUsers: React.FC = () => {
  const { t } = useLanguage();
  const { users, addUser, updateUser, roles, user: currentUser } = useAuth();
  const navigate = useNavigate();
  
  // Create State
  const [newUsername, setNewUsername] = useState('');
  const [newPassword, setNewPassword] = useState('');
  const [selectedRole, setSelectedRole] = useState(roles[0]?.name || '');

  // Edit State
  const [editingUser, setEditingUser] = useState<User | null>(null);
  const [editUsername, setEditUsername] = useState('');
  const [editRole, setEditRole] = useState('');
  const [editPassword, setEditPassword] = useState('');
  const [showEditModal, setShowEditModal] = useState(false);

  const handleAddUser = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newUsername || !selectedRole || !currentUser) return;
    
    // Note: ID will be generated by Supabase DB
    const newUser: User = {
      id: '', 
      username: newUsername,
      voen: currentUser.voen, // Enforce Tenant VOEN
      role: selectedRole,
      password: newPassword
    };
    
    try {
        await addUser(newUser);
        setNewUsername('');
        setNewPassword('');
        alert(t('user_added_success'));
    } catch (e: any) {
        alert("Error adding user: " + e.message);
    }
  };

  const openEditModal = (user: User) => {
      setEditingUser(user);
      setEditUsername(user.username);
      setEditRole(user.role);
      setEditPassword('');
      setShowEditModal(true);
  };

  const handleUpdateUser = async (e: React.FormEvent) => {
      e.preventDefault();
      if(!editingUser) return;
      
      const updates: Partial<User> = {
          username: editUsername,
          role: editRole
      };

      if (editPassword) {
          updates.password = editPassword;
      }

      try {
          await updateUser(editingUser.id, updates);
          setShowEditModal(false);
          setEditingUser(null);
          setEditPassword('');
          alert(t('update_success'));
      } catch (e: any) {
          alert('Failed to update: ' + e.message);
      }
  };

  return (
    <div className="space-y-8">
      {/* Mobile Back Button */}
      <div className="md:hidden mb-4">
          <button 
              onClick={() => navigate('/')} 
              className="flex items-center gap-2 text-slate-600 dark:text-slate-300 hover:text-blue-600 dark:hover:text-blue-400 font-medium p-2 -ml-2 rounded-lg active:bg-slate-100 dark:active:bg-slate-800"
          >
              <ChevronLeft size={20} /> 
              {t('previous')}
          </button>
      </div>

      <h1 className="text-2xl font-bold text-slate-800 dark:text-white">{t('admin_users')}</h1>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* Add User Form */}
          <div className="bg-white dark:bg-slate-800 p-6 rounded-xl shadow-sm border border-slate-100 dark:border-slate-700">
            <h2 className="text-lg font-semibold text-slate-700 dark:text-slate-200 mb-4 flex items-center gap-2">
                <UserPlus size={20} />
                {t('add_user')}
            </h2>
            <form onSubmit={handleAddUser} className="space-y-4">
               <div>
                  <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">{t('voen')}</label>
                  <input 
                    type="text" 
                    disabled
                    className="w-full rounded-lg border-slate-300 dark:border-slate-600 bg-slate-100 dark:bg-slate-700/50 dark:text-slate-400 p-2 cursor-not-allowed"
                    value={currentUser?.voen || ''}
                  />
                  <p className="text-xs text-slate-400 mt-1">You cannot change the VOEN.</p>
               </div>

               <div>
                  <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">{t('username')}</label>
                  <input 
                    type="text" 
                    required
                    className="w-full rounded-lg border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-700 dark:text-white p-2"
                    value={newUsername}
                    onChange={(e) => setNewUsername(e.target.value)}
                  />
               </div>

               <div>
                  <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">{t('password')}</label>
                  <input 
                    type="password" 
                    required
                    className="w-full rounded-lg border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-700 dark:text-white p-2"
                    value={newPassword}
                    onChange={(e) => setNewPassword(e.target.value)}
                  />
               </div>
               
               <div>
                  <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">{t('role')}</label>
                  <select
                    required
                    className="w-full rounded-lg border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-700 dark:text-white p-2"
                    value={selectedRole}
                    onChange={(e) => setSelectedRole(e.target.value)}
                  >
                    {roles.map(r => (
                        <option key={r.name} value={r.name}>{r.name}</option>
                    ))}
                  </select>
               </div>

               <button 
                 type="submit" 
                 className="bg-blue-600 text-white px-6 py-2 rounded-lg font-medium hover:bg-blue-700 transition-colors flex items-center gap-2"
               >
                 <Check size={18} />
                 {t('save')}
               </button>
            </form>
          </div>
      </div>

      {/* User List */}
      <div className="bg-white dark:bg-slate-800 rounded-xl shadow-sm border border-slate-100 dark:border-slate-700 overflow-hidden">
        <h2 className="text-lg font-semibold text-slate-700 dark:text-slate-200 p-6 border-b border-slate-100 dark:border-slate-700">{t('existing_users')}</h2>
        <div className="overflow-x-auto">
          <table className="w-full text-sm text-left text-slate-600 dark:text-slate-300">
             <thead className="text-xs text-slate-700 dark:text-slate-400 uppercase bg-slate-50 dark:bg-slate-700/50">
               <tr>
                 <th className="px-6 py-3">{t('voen')}</th>
                 <th className="px-6 py-3">{t('username')}</th>
                 <th className="px-6 py-3">{t('role')}</th>
                 <th className="px-6 py-3 text-right">{t('actions')}</th>
               </tr>
             </thead>
             <tbody>
                {users.map(u => (
                  <tr key={u.id} className="bg-white dark:bg-slate-800 border-b dark:border-slate-700 hover:bg-slate-50 dark:hover:bg-slate-700">
                    <td className="px-6 py-4 font-mono text-slate-500 dark:text-slate-400">{u.voen}</td>
                    <td className="px-6 py-4 font-bold text-slate-900 dark:text-white">{u.username}</td>
                    <td className="px-6 py-4">
                        <span className="bg-blue-100 dark:bg-blue-900/30 text-blue-800 dark:text-blue-300 text-xs font-semibold px-2.5 py-0.5 rounded">{u.role}</span>
                    </td>
                    <td className="px-6 py-4 text-right">
                         <button onClick={() => openEditModal(u)} className="text-blue-600 hover:bg-blue-50 dark:text-blue-400 dark:hover:bg-blue-900/20 p-2 rounded-lg transition-colors flex items-center gap-1 text-xs ml-auto">
                            <Edit size={16} /> {t('edit')}
                         </button>
                    </td>
                  </tr>
                ))}
             </tbody>
          </table>
        </div>
      </div>

      {/* Edit User Modal */}
      {showEditModal && editingUser && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
            <div className="bg-white dark:bg-slate-800 rounded-xl shadow-xl max-w-lg w-full p-6 animate-in fade-in zoom-in-95">
                <div className="flex justify-between items-center mb-4">
                    <h2 className="text-xl font-bold dark:text-white">{t('edit_user')}</h2>
                    <button onClick={() => setShowEditModal(false)} className="text-slate-500"><X size={20}/></button>
                </div>
                <form onSubmit={handleUpdateUser} className="space-y-4">
                    <div>
                        <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">{t('username')}</label>
                        <input 
                            type="text" 
                            required
                            className="w-full rounded-lg border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-700 dark:text-white p-2"
                            value={editUsername}
                            onChange={(e) => setEditUsername(e.target.value)}
                        />
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">{t('role')}</label>
                        <select
                            required
                            className="w-full rounded-lg border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-700 dark:text-white p-2"
                            value={editRole}
                            onChange={(e) => setEditRole(e.target.value)}
                        >
                            {roles.map(r => (
                                <option key={r.name} value={r.name}>{r.name}</option>
                            ))}
                        </select>
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">{t('password')}</label>
                        <input 
                            type="password" 
                            className="w-full rounded-lg border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-700 dark:text-white p-2"
                            value={editPassword}
                            onChange={(e) => setEditPassword(e.target.value)}
                            placeholder="New password"
                        />
                        <p className="text-xs text-slate-400 mt-1">{t('leave_blank_password')}</p>
                    </div>
                    <div className="flex justify-end gap-3 mt-6">
                        <button type="button" onClick={() => setShowEditModal(false)} className="px-4 py-2 text-slate-600 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-700 rounded">{t('cancel')}</button>
                        <button type="submit" className="px-4 py-2 bg-green-600 text-white rounded hover:bg-green-700">{t('update')}</button>
                    </div>
                </form>
            </div>
        </div>
      )}
    </div>
  );
};
